import { mkdtempSync, rmSync, writeFileSync, mkdirSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { runExportsResolutionTest } from '../../../tooling/tests/exports-resolution.mjs'

// Each scenario uses a fresh temp project so describe blocks generated by the
// helper don't collide.

describe('exports-resolution helper', () => {
	describe('passing scenario: exports map matches src/ folders exactly', () => {
		let root: string

		beforeAll(() => {
			root = mkdtempSync(join(tmpdir(), 'jt-exports-pass-'))
			writeFileSync(
				join(root, 'package.json'),
				JSON.stringify({
					name: 'fake-lib',
					exports: {
						'.': './dist/index.js',
						'./foo': './dist/foo/index.js',
						'./bar': './dist/bar/index.js',
					},
				})
			)
			mkdirSync(join(root, 'src/foo'), { recursive: true })
			mkdirSync(join(root, 'src/bar'), { recursive: true })
		})

		afterAll(() => {
			rmSync(root, { recursive: true, force: true })
		})

		it('generates passing assertions for foo and bar', () => {
			runExportsResolutionTest({
				packageJsonPath: join(root, 'package.json'),
				srcDir: join(root, 'src'),
			})
			// The helper generates its own describe/it blocks; if any fails, vitest
			// will surface them. Reaching this line means the setup ran cleanly.
		})
	})

	it('throws when package.json has no exports field', () => {
		const root = mkdtempSync(join(tmpdir(), 'jt-exports-noexports-'))
		writeFileSync(join(root, 'package.json'), JSON.stringify({ name: 'no-exports' }))
		mkdirSync(join(root, 'src/foo'), { recursive: true })

		expect(() =>
			runExportsResolutionTest({
				packageJsonPath: join(root, 'package.json'),
				srcDir: join(root, 'src'),
			})
		).toThrow(/no exports map/)

		rmSync(root, { recursive: true, force: true })
	})

	it('respects excludeDirs', () => {
		const root = mkdtempSync(join(tmpdir(), 'jt-exports-exclude-'))
		writeFileSync(
			join(root, 'package.json'),
			JSON.stringify({
				name: 'fake-lib',
				exports: {
					'.': './dist/index.js',
					'./foo': './dist/foo/index.js',
				},
			})
		)
		mkdirSync(join(root, 'src/foo'), { recursive: true })
		mkdirSync(join(root, 'src/tests'), { recursive: true })
		mkdirSync(join(root, 'src/common'), { recursive: true })

		// If excludeDirs weren't respected, the helper would assert that
		// `./tests` and `./common` should exist in the exports map and fail.
		runExportsResolutionTest({
			packageJsonPath: join(root, 'package.json'),
			srcDir: join(root, 'src'),
			excludeDirs: ['tests', 'common'],
		})

		rmSync(root, { recursive: true, force: true })
	})
})
