import path from 'node:path'
import fs from 'fs-extra'
import type { ProjectConfig } from '../commands/setup.js'

export async function generateGitLabCI(config: ProjectConfig, targetDir: string) {
	const yamlPath = path.join(targetDir, '.gitlab-ci.yml')
	await fs.writeFile(yamlPath, renderGitLabCI(config))
	return '.gitlab-ci.yml'
}

function lintCommand(config: ProjectConfig): string {
	if (config.linting.tool === 'biome' || config.linting.tool === 'both') return 'pnpm check'
	return 'pnpm lint'
}

function renderGitLabCI(config: ProjectConfig): string {
	const hasTypeScript = config.typescript.enabled
	const hasTests = config.testing.framework !== 'none'
	const hasLint = config.linting.tool !== 'none'
	const hasBuild = config.bundler !== 'none'

	const stages: string[] = []
	if (hasLint || hasTypeScript || hasTests) stages.push('test')
	if (hasBuild) stages.push('build')
	if (stages.length === 0) stages.push('test')

	const jobs: string[] = []

	if (hasLint) {
		jobs.push(`lint:
  stage: test
  script:
    - ${lintCommand(config)}`)
	}

	if (hasTypeScript) {
		jobs.push(`typecheck:
  stage: test
  script:
    - pnpm typecheck`)
	}

	if (hasTests) {
		const testCmd =
			config.testing.framework === 'vitest'
				? 'pnpm exec vitest run'
				: config.testing.framework === 'playwright'
					? 'pnpm test:e2e'
					: 'pnpm test'
		jobs.push(`test:
  stage: test
  script:
    - ${testCmd}`)
	}

	if (hasBuild) {
		jobs.push(`build:
  stage: build
  script:
    - pnpm build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week`)
	}

	return `# .gitlab-ci.yml — generated by @rtorcato/js-tooling
# Customize stages and jobs to fit your pipeline.

image: node:22

stages:
${stages.map((s) => `  - ${s}`).join('\n')}

variables:
  PNPM_CACHE_FOLDER: .pnpm-store

cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - .pnpm-store
    - node_modules

default:
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest --activate
    - pnpm config set store-dir "$PNPM_CACHE_FOLDER"
    - pnpm install --frozen-lockfile

${jobs.join('\n\n')}
`
}
